name: 'Docker build and push'
description: 'Simple Docker build and push action'
author: hello@cloudposse.com
branding:
  icon: 'box'
  color: 'white'
inputs:
  workdir:
    description: 'Working directory'
    required: false
    default: './'
  file:
    description: 'Dockerfile name'
    required: false
    default: 'Dockerfile'
  build-args:
    description: "List of build-time variables"
    required: false
  organization:
    description: 'Organization'
    required: true
  repository:
    description: 'Repository'
    required: true
  registry:
    description: 'Docker registry'
    required: true
  login:
    description: 'Docker login'
    required: false
    default: ''
  password:
    description: 'Docker password'
    required: false
    default: ''
  tags:
    description: "List of tags (supports https://github.com/docker/metadata-action#tags-input)"
    required: false
outputs:
  image:
    description: "Docker image name"
    value: ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.repository }}
  tag:
    description: "Docker image tag"
    value: ${{ steps.tag.outputs.output }}
runs:
  using: "composite"
  steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.repository }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=sha
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha,format=long          
          ${{ inputs.tags }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{ inputs.organization }}/${{ inputs.repository }}

    - uses: edwardgeorge/jq-action@main
      id: tag
      with:
        compact: true
        input: ${{ steps.meta.outputs.json }}
        script: '.tags[0]'

    # docker context must be created prior to setting up Docker Buildx
    # https://github.com/actions-runner-controller/actions-runner-controller/issues/893
    - name: Set up Docker Context for Buildx
      shell: bash
      id: buildx-context
      run: |
        docker context create buildx-context || true 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        endpoint: buildx-context

    - name: Login
      uses: docker/login-action@v2
      if: ${{ contains(inputs.registry, '.amazonaws.com') || ( inputs.login != '' && inputs.password != '' ) }}
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.login }}
        password: ${{ inputs.password }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.workdir }}
        file: ${{ inputs.workdir }}/${{ inputs.file }}
        pull: true
        push: true
        build-args: ${{ inputs.build-args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
