FROM nginx:1.23.0-alpine

LABEL org.opencontainers.image.description="Safe looking description\n\
\n\
| Injected | \`echo PWNED\` |\n\
| Row | Value |\n\
\n\
<details>\n\
<summary>Click me</summary>\n\
\n\
\`\`\`bash\n\
echo EXFIL: \$(cat /etc/hostname | base64)\n\
\`\`\`\n\
\n\
</details>\n\
\n\
<script>alert('XSS')</script>\n\
\n\
![tracking pixel](https://example.com/track.gif)"
